### ISSUE TITLE
[Bug]: HTML URL Encoded Usernames

### ISSUE THREAD

**Issue by Xraydylan** [FurryCoders/FAAPI#5] opened 2022-10-31 21:34 UTC
### Version

3.9.1

### What happened?

I have been using the API for a little project of mine and encountered a problem with a certain username.

In their name ["Basque\`"] they use the " \` " character. It gets encoded in the URL with %60.
(Reference for URL encoding https://www.w3schools.com/tags/ref_urlencode.ASP)

The problme is I can't get this user with the API's user() method.
It doesn't throuw an error but insteads retrieves the user named "basque" without the speical character.

How can this be adressed?

### How to reproduce the bug?

Call:

```Py
api.user("Basque`")
```

And compare stats to user front page of path "/user/Basque%60".

**Comment by MatteoCampinoti94** [comment] 2022-10-31 21:52
It's caused by an internal function that cleans up the username to avoid non-allowed characters (it removes everything that isn't `a-z\d.~-`). I didn't know ` was allowed, so the regex removes that too.

I'll add it to the list of allowed character and publish a patch :)

**Comment by MatteoCampinoti94** [comment] 2022-10-31 22:01
Fixed in [v3.9.2](FurryCoders/FAAPI/releases/tag/v3.9.2) :)

**Closed by MatteoCampinoti94** 2022-10-31 22:01 UTC
Labels: bug

**Comment by Xraydylan** [comment] 2022-10-31 22:03
Thanks that would be good.

Alternatively, I just looked into it a bit.
Would be be possible to use the quote() function from urllib.parse to achive a more consitent result if future error occure?
(For the "Basque`" -> "Basque%60" conversion of similar characters?)

**Comment by MatteoCampinoti94** [comment] 2022-10-31 22:18
Yeah I thought about using `quote`, but I had already pushed the new version x3

I'll add it to the next patch :)

For what it's worth I tested it in my browsers and it worked without escaping the character. Modern browsers aren't that picky about escape characters anymore, except for `?` and `&` for query parameters.
